name: composite_subscription
version: 0.1.0
homepage: https://github.com/JosephMoniz/dart-composite-subscription
description: >
  A composite pattern for multiple stream subscriptions
author: Joseph Moniz <joseph.moniz@gmail.com>